### ISSUE TITLE
Remove one of the extensions in vscode

### ISSUE THREAD

**Issue by ychechik** [ChaosinaCan/vscode-remote-x11#5]
BTW: Great work works perfectly for me.
Maybe you can also add a logo for the extension...

Remove one of the extensions in vscode:
![image](https://user-images.githubusercontent.com/58138282/77247584-4e416400-6c3b-11ea-9a2d-89c4d4402d62.png)

**Comment by ChaosinaCan** [comment]
Are you saying you expect uninstalling Remote X11 to uninstall the SSH extension as well?

It seems like an issue with VS Code rather than my extension if uninstalling an extension pack (https://github.com/ChaosinaCan/vscode-remote-x11/blob/master/extension/package.json#L24) doesn't uninstall everything in the pack too.

**Comment by DominikReinert** [comment]
I think he wants you to merge the two extensions into one. I would agree on that, but I also dont know all the use cases you might want to cover by splitting it into two

**Comment by ychechik** [comment]
What @DominikReinert said

**Comment by ChaosinaCan** [comment]
Oh. This wouldn't be possible without two extensions for SSH. One runs on the remote computer to set the DISPLAY variable, and the other runs on the local computer to create the an SSH connection with X forwarding enabled.

The two parts do different things and activate in different scenarios, so combining them into one doesn't make sense. I'm not even sure if VS Code allows the same extension to run on both computers at the same time either.
