### ISSUE TITLE
Can not set the ssh port in X11 extension

### ISSUE THREAD

**Issue by xiaqian369** [ChaosinaCan/vscode-remote-x11#9]
@ChaosinaCan Sorry for bothering you, I can work flawlessly with a new session by SecrueCRT or PuTTY in background like @wrobelda, but if I close the SecrueCRT or PuTTY, using your extension, it does not work, the failure info is "Could not connect to any X display.". Could you please provide a detailed config instruction on your https://marketplace.visualstudio.com/items?itemName=spadin.remote-x11 page? like how to config in vscode, how to config in remote-ssh computer, does your extension need to install in remote machine? etc.

@xiaqian369 I just published an update with improved error logging and some troubleshooting steps in the readme. If you still can't get it working, please use my extension's issues page. Thanks!

Thank you for your response in issue [https://github.com/microsoft/vscode-remote-release/issues/267](url), now I can get my problem. It is the ssh-port that I really need to connect is not 22, but a different number, for some reasons of my company. So, can this extension automaticlly grap  the "ssh port" in user.setting or provide a interface to config the "ssh port" mannually?

**Comment by xiaqian369** [comment]
The X11 out put log is :   
Setting up display for remote "ssh-remote".
Connecting to SSH mayc@192.168.89.252 port 22
Error: Timed out while waiting for handshake

but this log also puzzed me. Because the ip "192.168.89.252" is the local ip of the remote linux server in its subnet, so does the extension runs on the the remote server?  I draw a draft of my connection for your infomation:

                     59.172.63.11:12200                 subnet        ip:192.168.89.252
     my laptop----------------my Company Firewall---------------------- linux server

I can ssh through the address:  59.172.63.11:1220 to connect the linux server

**Comment by ChaosinaCan** [comment]
The extension runs in two parts:

1. The main part (Remote X11) runs on the remote server. It's responsible for setting the `DISPLAY` variable.
2. The second part (Remote X11 (SSH)) runs locally. It creates the second SSH connection to the remote server to make X11 forwarding work.

This is all supposed to work as follows:

1. VS Code creates an SSH connection to the remote server.
2. The main extension activates on the server. It sees that you're using an SSH connection, so it [grabs the user, address, and port out of the `SSH_CONNECTION` variable](https://github.com/ChaosinaCan/vscode-remote-x11/blob/master/extension/src/extension.ts#L80), then asks the SSH extension to make a second SSH connection with those settings.
3. The SSH extension creates an SSH connection with X11 forwarding enabled, figures out what `DISPLAY` got set to, and sends that back to the main extension.
4. The main extension sets `DISPLAY` on the remote server to match.

Here's an attempt at visualizing this:

![image](https://user-images.githubusercontent.com/57683567/79765348-1e45b900-82ec-11ea-90a4-d3904e8c9584.png)

So the port and address should match whatever VS Code is using for its remote connection, unless it's somehow not setting `SSH_CONNECTION` properly. How have you configured VS Code to connect to your remote server? 

Also, can you check the logs for "Remote X11 (SSH)" as well? I suspect there will be more helpful info in those logs.

**Comment by RexBarker** [comment]
Hi ChaosinaCan,
Nice extension.  I'm having the same problem as above.  I use a public key to connect to my remote station, but I don't use port for SSH.
Where do I should I specify the connection variable "SSH_CONNECTION" for my given configuration?  I tried defining it as an environment variable on the remote machine through the _launch.json_ .  But nothing is being picked up.  It still defaults to port 22.

**Comment by RexBarker** [comment]
@ChaosinaCan 
It would be nice if you had another setting variable for the port such as: 
`remoteX11.SSH.port`

**Comment by ChaosinaCan** [comment]
@RexBarker 

The `SSH_CONNECTION` variable is set by SSH (https://unix.stackexchange.com/questions/120080/what-are-ssh-tty-and-ssh-connection). When you connect to an SSH target in vscode, it gets set automatically, so you don't need to set it. The last two parts of the variable are the server's IP address and port, which is what my extension uses.

When you're connected to an SSH target, could you open a terminal and run this?

```sh
echo $SSH_CONNECTION
```

It should print out something like `192.168.86.50 22858 192.168.86.30 22`, except that last number should match the port you're using (not 22). If it matches the port you want to use but my extension is still using port 22, then I can figure out why and fix that. If it says 22 instead of the port you want to use, then probably one of two things is happening:

1. You aren't actually connecting on port 22. You need to edit your SSH configuration in vscode and change the port (F1 > Remote-SSH: Open Configuration File... or F1 > Remote-SSH: Add New SSH Host...).
2. vscode is doing some sort of port trickery and `SSH_CONNECTION` doesn't match what's actually being used, in which case I can add a per-machine setting to override the address and/or port used.

**Comment by RexBarker** [comment]
@ChaosinaCan 
I realize now that issue comes from my router definition.  On my local network (if I was to sit at home and connect on my own subnet), the machine level SSH port is 22.  I didn't change this for all of my machines.  So on my local network, I would connect with `ssh linuxBoxFoo.local`.  Then, for the outside, I remap the ports of each box via port fowarding (router itself).  So connecting from the outside would be `ssh -p 1234 linuxBoxFoo.rexbarker.org`.  Normally this works fine if I use the `-Y` trusted X11 forwarding.

The issue is that I need to connect with the port I use from the outside.  I can connect normally with the VS code "Remote - SSH" extension.  It seems your extension is mining the port information from this on the remote side (where it is true that the `SSH_CONNECTION xxx.xxx.xx xx.xx xx.xx 22` is correct for the machine local subnet...not to the outside.  Using my remote login, your VS code "Remote - SSH" extension should the correct value for port (as defined by my `~/.ssh/ssh_config` file on my current machine...not from the remote machine)

So what I'm looking for is a way to define the port myself, instead of the add-in trying to extract the port definition from the `SSH_CONNECTION` definition

**Comment by xiaqian369** [comment]
@ChaosinaCan 
hi, thank you.
The issue what @RexBarker said is exact. Now i provide you the log info:

1. the output of "Rmote X11" is:
    Setting up display for remote "ssh-remote".
    Connecting to SSH mayc@192.168.89.252 port 22
    Error: Timed out while waiting for handshake
2. the output of "Remote X11 (SSH)" is:
    Connecting to mayc@192.168.89.252 port 22
    Error: Timed out while waiting for handshake
3. the display of "echo $SSH_CONNECTION" in my vscode integret terminal bash is:
    113.222.219.77 22695 192.168.89.252 22
    (note: if I use  SecureCRT to connect my linux server through ssh, the display of "echo 
    $SSH_CONNECTION" in SecureCRT is:
    113.222.219.77 24209 192.168.89.252 22)

the detailed connection is:
![image](https://user-images.githubusercontent.com/36779951/80058568-328fed00-855c-11ea-8abe-2e05b68ebebc.png)

In this toplogic net, the local vscode in my laplop can connect the linux server by using ssh through address:
59.172.63.11:12200
and, i can work well with a SecureCRT opened backgroud as the second ssh connection, In this good situation, my  "echo $SSH_CONNECTION" is as the 3rd point I listed above.

Based above, I suspect the problem maybe:
     the X11 extension running on the linux server grapped its local port 22 and its local address 192.168.89.252, but this is not the real port and address (or it's real, but it just through the 192.168.89.252:22 to connect to the router, the laptop is also connect to the router? ). I've no idea whether it should grab the port such like 22695 or 24209?  
     I think the extension should work just like an integrete SecureCRT of vscode, which is runing in my local laptop, so, how does the SecureCRT process these procedures? 

I will give you the steps when I use SecureCRT, this works well:

0. set the /etc/.sshd/sshd_config properly in remote linux server.
1. open vscode, connect with the linux server though the extension "remote-SSH", the address is:
59.172.63.11:12200
2. open a SecureCRT, and create a SSH session with address 59.172.63.11:12200, at the same time, enable the X11 forwarding in SecureCRT, the screenshot is:
![image](https://user-images.githubusercontent.com/36779951/80065236-5fe49700-856c-11ea-8111-3451291f1fac.png)
3. lookup the $DISPLAY env variable in SecureCRT, such as: localhost:10.0
4. set "export DISPLAY localhost:10.0" in vscode integrate terminal bash.

Above is my detailed info, for your infomation,  thanks for your effort, hope it can work well with the vscode, cause it is great.

**Comment by ChaosinaCan** [comment]
I just published version 1.2.0 which adds `remoteX11.SSH.host` and `remoteX11.SSH.port` settings to change the hostname/address and port that Remote X11 uses. To use them, connect vscode to your remote machine, open settings, switch to the "Remote" tab, and search for "remote x11". Set them to the hostname/address and port you use to connect from the outside.

(I chose not to read from `~/.ssh/ssh_config` because I don't have a good way to know which configuration you're using or whether that's even the right config file.)

Let me know if that works for you.

**Comment by xiaqian369** [comment]
@ChaosinaCan 
I have tried the version 1.2.0.  The connection seems to work,  but a nother issue happend, the terminal  hang.  Detailed info:

1. output of "Remote X11(SSH)" is:
```
Connecting to mayc@59.172.63.11 port 12200
Connection ready. Setting up display...
Command for host "59.172.63.11" is: bash -c "echo DISPLAY=$DISPLAY"
----- Begin output from host -----

Welcome to Ubuntu 18.04 LTS (GNU/Linux 4.15.0-72-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage


 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

442 packages can be updated.
27 updates are security updates.

*** System restart required ***
Last login: Fri Apr 24 13:15:49 2020 from 113.222.219.77

mayc@user:~$ bash -c "echo DISPLAY=$DISPLAY"
DISPLAY=localhost:10.0
mayc@user:~$ 
----- End output from host -----
Display ready: localhost:10.0
Parser disposed. 
```
2. output of "Remote X11(SSH)" is:
```
Setting up display for remote "ssh-remote".
Connecting to SSH mayc@59.172.63.11 port 12200
DISPLAY = localhost:10.0
```

3. the user setting in local laptop is:
![image](https://user-images.githubusercontent.com/36779951/80179678-aa7d1680-8633-11ea-9d00-e44d855a348e.png)

4. the user setting of Remote is:
![image](https://user-images.githubusercontent.com/36779951/80179901-1e1f2380-8634-11ea-90c9-54e886a8bdec.png)

5. The python file is very simple, just to show a image:
```
from skimage import img_as_ubyte, io, img_as_float

ski_image =  io.imread("imageData/1708.jpg")
io.imshow(ski_image)
io.show()
```

but, when exacute the "run", the intergrate python teminal suspend, no print out, even the "ctrl +c" command does not work. Seems like someting was blocked in the backgroud.

**Comment by ChaosinaCan** [comment]
I tried running the same commands on my (much simpler) network, and it did display the image, so something must not be right with either your settings or how my extension handles your setup.

Does your script display anything when a regular SSH connection with X forwarding (not going through my extension)? If not, make sure your X server is running.

If it does work outside of my extension, check the "Remote X11 (SSH)" logs _after_ you run the script. It should log something like "x11 accept: 127.0.01" whenever an application tries to display something. If nothing is getting logged, then we need to figure out why your script isn't sending anything to the forwarded display. Try adding something to your script to make sure `DISPLAY` is set in the script's environment, such as:

```py
import os
print('DISPLAY = ' + os.environ['DISPLAY'])
```

If "x11 accept" is getting logged, then things are getting sent over SSH to your local computer, so we need to figure out why your X server isn't displaying them. The first thing I'd check is if your `remoteX11.display` setting matches the display number on which your X server is listening.

**Comment by xiaqian369** [comment]
Sorry, i had on bussiness for several days.  Now i am answering your questions:
1. Does your script display anything when a regular SSH connection with X forwarding (not going through my extension)?
answer: Yes, if I don't use your extension, it can display well.  I can display using the SecureCRT as the X11 forwarding. But if I use your extension as the X forwording, it suspend.

2. "Remote X11 (SSH)" log is:

![1](https://user-images.githubusercontent.com/36779951/81651218-1ac5cd80-9465-11ea-9432-06b9f2d6f407.png)


here the ssh port is 22252 which is different from the comments I listed above, but it doesn't matter, because the my company  changed it from 12200 to 22252  about the ssh port mapping.

**Comment by xiaqian369** [comment]
The log of "Remote X11" is:
![2](https://user-images.githubusercontent.com/36779951/81651670-6bd5c180-9465-11ea-8590-9172df0f1dac.png)
The python code I ran is :
![3](https://user-images.githubusercontent.com/36779951/81652417-4bf2cd80-9466-11ea-8352-754dcce44faa.png)

**Comment by joelspadin-garmin** [comment]
It looks like my extension is creating the SSH connection and setting `DISPLAY` correctly. The Python script thinks it's connected to the forwarded display, which is why it hangs instead of printing an error and exiting.

I think the issue is now that data is getting to the local PC, but it's either being blocked or not properly sent to the X server once it gets there. Since you are using display number 10 in your settings, data will be sent to port 6010. Do you have a firewall that might be blocking code.exe from sending data to that port?

Also, is the X server on your local PC using display number 10? The forwarded display, "localhost:10.0", has no relation to the display number for your X server. For example, when using VcXsrv, your **Remote X11: Display** setting should match the number you set when configuring it here: 

![image](https://user-images.githubusercontent.com/57683567/81729714-0fb57200-9452-11ea-8c8b-31d155af9dc4.png)

**Comment by ChaosinaCan** [comment]
I just noticed I posted that on my work account, but the above comment is also me.

**Comment by xiaqian369** [comment]
@ChaosinaCan Thank you, it works now, I found I configured a wrong number in my VcXsrv.  Now it works excellently.

Now i provide my whole configuration now:
![Remote_setting](https://user-images.githubusercontent.com/36779951/82979405-8db07600-a019-11ea-87c0-6b194ae4a189.png)
![user_setting](https://user-images.githubusercontent.com/36779951/82979428-9739de00-a019-11ea-97e4-be49b94563e4.png)
![vcXsrv](https://user-images.githubusercontent.com/36779951/82979438-a02aaf80-a019-11ea-9bea-3e775386fd92.png)

**Comment by ChaosinaCan** [comment]
Great! Feel free to re-open this or create another issue if you run into any more problems.
